# Generated by Django 5.2.1 on 2025-06-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم الطبيب')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الزيارة')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('treatment', models.TextField(verbose_name='العلاج')),
                ('prescription', models.TextField(blank=True, verbose_name='الوصفة الطبية')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
            ],
            options={
                'verbose_name': 'ملف طبي',
                'verbose_name_plural': 'الملفات الطبية',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم المريض')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
            },
        ),
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problematic_teeth', models.CharField(max_length=250, verbose_name='الأسنان التي بها مشكلة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalrecord', verbose_name='الملف الطبي')),
            ],
            options={
                'verbose_name': 'رسم الأسنان',
                'verbose_name_plural': 'رسومات الأسنان',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='المريض'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الموعد')),
                ('time', models.TimeField(verbose_name='وقت الموعد')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor', verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(choices=[(11, 'Tooth 11'), (12, 'Tooth 12'), (13, 'Tooth 13'), (14, 'Tooth 14'), (15, 'Tooth 15'), (16, 'Tooth 16'), (17, 'Tooth 17'), (18, 'Tooth 18'), (21, 'Tooth 21'), (22, 'Tooth 22'), (23, 'Tooth 23'), (24, 'Tooth 24'), (25, 'Tooth 25'), (26, 'Tooth 26'), (27, 'Tooth 27'), (28, 'Tooth 28'), (31, 'Tooth 31'), (32, 'Tooth 32'), (33, 'Tooth 33'), (34, 'Tooth 34'), (35, 'Tooth 35'), (36, 'Tooth 36'), (37, 'Tooth 37'), (38, 'Tooth 38'), (41, 'Tooth 41'), (42, 'Tooth 42'), (43, 'Tooth 43'), (44, 'Tooth 44'), (45, 'Tooth 45'), (46, 'Tooth 46'), (47, 'Tooth 47'), (48, 'Tooth 48')])),
                ('condition', models.CharField(max_length=100)),
                ('treatment_plan', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
